VS5:
  name: Vegemite Scroll
  packs:
    -
      quantity: 3
      price: 6.99
    -
      quantity: 5
      price: 8.99
MB11:
  name: Blueberry Muffin
  packs:
    -
      quantity: 2
      price: 9.95
    -
      quantity: 5
      price: 16.95
    -
      quantity: 8
      price: 24.95
CF:
  name: Croissant
  packs:
    -
      quantity: 3
      price: 5.95
    -
      quantity: 5
      price: 9.95
    -
      quantity: 9
      price: 16.99